"""Initial tables

Revision ID: 331b426e08ea
Revises: 
Create Date: 2025-11-21 13:13:37.847852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331b426e08ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_friendship_created', ['created_at'], unique=False)
        batch_op.create_index('idx_friendship_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendship_status'), ['status'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendship_status'))
        batch_op.drop_index('idx_friendship_status')
        batch_op.drop_index('idx_friendship_created')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
